{% set name = "autogluon.vision" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 381ca65386793cc304bf4d439622f33553dc6c7afa09a22a2be4584319a8bf09

build:
  skip: true  # [win]
  skip: true  # [py>=310]
  script: {{ PYTHON }} -m pip install ./vision -vv
  number: 0
  script_env:
    - RELEASE=1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy  <1.24,>=1.21                    # [build_platform != target_platform]
    # Fixed missing libGL.so.1 error. See https://conda-forge.org/docs/maintainer/knowledge_base.html#libgl
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
  host:
    - python
    - pip
    - xorg-libxfixes  # [linux]
  run:
    - python
    - numpy <1.24,>=1.21
    - pandas !=1.4.0,<1.6,>=1.2.5
    - gluoncv <0.10.6,>=0.10.5
    - pillow <=9.4.0,>=9.3.0
    - timm <0.7.0,>=0.5.4
    - matplotlib-base
    - autogluon.core =={{ version }}
    - autogluon.multimodal =={{ version }}

test:
  imports:
    - autogluon.vision
  commands:
    - python -c "from autogluon.vision import __version__ as v; assert v == '{{ version }}', f'{v} != {{ version }}'"
  requires:
    - pip

about:
  home: https://pypi.org/project/autogluon.vision
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Innixma
    - giswqs
